cask_args appdir: '/Applications'

# install commandline utils
brew 'antigen'
brew 'gh'
brew 'go'
brew 'grc'
brew 'mas'
brew 'mongodb-community'
brew 'the_silver_searcher'
brew 'vim'
brew 'wget'

# install apps
cask 'brave-browser'
cask 'dropbox'
cask 'figma'
cask 'firefox'
cask 'iterm2'
cask 'mongodb-compass'
cask 'notion'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'zoom'
